# For more info on HTTP files go to https://aka.ms/vs/httpfile

@GokeWebApp_HostAddress = https://localhost:7050

GET {{GokeWebApp_HostAddress}}/weather/
Accept: application/json

###

GET {{GokeWebApp_HostAddress}}/weather/2

###

Post {{GokeWebApp_HostAddress}}/weather
Content-Type: application/json

{
  "id": 0,
  "summary": "nice time"
  
}

###